[supervisord]
nodaemon=true
#user=devuser
logfile=/var/log/supervisord.log
pidfile=/var/run/supervisord.pid

[program:nvim-headless]
command=nvim --headless --listen 0.0.0.0:7778
autostart=true
autorestart=true

[program:opencode]
command=opencode web --port 4096 --hostname 0.0.0.0
autostart=true
autorestart=true
