# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

if [ ! -f /usr/local/etc/zsh_env_setup ]; then
	echo "export ZSH=$HOME/.oh-my-zsh" > /usr/local/etc/zsh_env_setup
	echo "DEFAULT_USER=$USER" >> /usr/local/etc/zsh_env_setup
fi

source /usr/local/etc/zsh_env_setup

source /usr/local/opt/powerlevel9k/powerlevel9k.zsh-theme

COMPLETION_WAITING_DOTS="true"

plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

source $ZSH/oh-my-zsh.sh

# User configuration

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# POWERLINE9K
POWERLEVEL9K_MODE="nerdfont-complete"

POWERLINE9K_PROMPT_ADD_NEWLINE=true

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(context dir vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status root_indicator background_jobs)

POWERLEVEL9K_SHORTEN_STRATERGY="truncate_to_last"
POWERLEVEL9K_SHORTEN_DIR_LENGTH=2
POWERLEVEL9K_DIR_SHOW_WRITABLE=true

# Powerline color config
POWERLEVEL9K_STATUS_OK_BACKGROUND='004'
POWERLEVEL9K_STATUS_OK_FOREGROUND='015'
POWERLEVEL9K_STATUS_ERROR_BACKGROUND='001'
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='015'

# Powerline icon config
POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\UE0B8'
POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\UE0BE'

POWERLEVEL9K_HOME_ICON='\UF7DB'
POWERLEVEL9K_HOME_SUB_ICON='\UF07C'
POWERLEVEL9K_FOLDER_ICON='\UF07B'
POWERLEVEL9K_ETC_ICON='\UE5FC'
POWERLEVEL9K_LOCK_ICON='\UF023'

POWERLEVEL9K_VCS_UNSTAGED_ICON='\UF421'
POWERLEVEL9K_VCS_STAGED='\UF055'
POWERLEVEL9K_VCS_UNTRACKED_ICON='\UF059'
POWERLEVEL9K_VCS_BRANCH_ICON='\UE725 '


export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
path+=("/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands")
export PATH
export PATH=/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/opt/local/bin:/opt/local/sbin


alias lamp='/Users/jakobstendahl/.lamp.sh'
alias uio-linux='ssh -YC jakobste@login.ifi.uio.no'
