# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Check if env setup file exists
if [ ! -f ~/.zsh_env_setup ]; then
	echo "export ZSH=$HOME/.oh-my-zsh" > ~/.zsh_env_setup
	echo "DEFAULT_USER=$USER" >> ~/.zsh_env_setup
fi

# Source env setup file
source ~/.zsh_env_setup

# Source powerlevel10k theme
case "$OSTYPE" in
    darwin*)
        source /usr/local/opt/powerlevel10k/powerlevel10k.zsh-theme;;
    linux*)
        ZSH_THEME="powerlevel10k/powerlevel10k";;
esac

COMPLETION_WAITING_DOTS="true"

# Setup plugins
plugins=(
  git
  zsh-autosuggestions
  zsh-syntax-highlighting
)

# Setup oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Modify locale and path
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Set vim as default editor
# export EDITOR=$(which vim)

# Add aliases
alias lsp="ps -ax | grep"
alias lsa="ls -la"
alias lsg="ls | grep"
alias lsag="ls -la | grep"
alias ls="tput setaf 3 && echo \"'lsa' for 'ls -la', \n'lsg' for 'ls | grep',\n'lsag' for 'ls -la | grep',\n'lsp' for 'ps -ax |grep'\" && tput sgr0 && ls"
alias notes="vim ~/Documents/notes.txt"
alias todo="vim ~/Documents/todo.txt"

# man pages in colors
man() {
    LESS_TERMCAP_md=$'\e[01;31m' \
    LESS_TERMCAP_me=$'\e[0m' \
    LESS_TERMCAP_se=$'\e[0m' \
    LESS_TERMCAP_so=$'\e[01;44;33m' \
    LESS_TERMCAP_ue=$'\e[0m' \
    LESS_TERMCAP_us=$'\e[01;32m' \
    command man "$@"
}

[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

case "$OSTYPE" in
    darwin*)
        path+=("$(readlink /Users/$DEFAULT_USER/bin)")
        path+=("/Library/TeX/texbin")
        path+=("/usr/local/share/dotnet")
        path+=("/usr/local/sbin")
        export PATH

        alias krak='/Applications/GitKraken.app/Contents/MacOS/GitKraken -p "$(PWD)" &>> /dev/null &'
        
        #THIS MUST BE AT THE END OF THE FILE FOR SDKMAN TO WORK!!!
        export SDKMAN_DIR="/Users/jakobstendahl/.sdkman"
        [[ -s "/Users/jakobstendahl/.sdkman/bin/sdkman-init.sh" ]] && source "/Users/jakobstendahl/.sdkman/bin/sdkman-init.sh"
    ;;
    linux*)
        alias pbcopy='xsel --clipboard --input'
        alias pbpaste='xsel --clipboard --output'
    ;;
esac
